### ISSUE TITLE
[store] Store panics on Entry::drop()

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#152]
```
thread '<main>' panicked at 'Tried to update a non borrowed entry.', /home/m/archive/development/rust/imag/libimagstore/src/store.rs:179
```

Code to reproduce: #136 at https://github.com/matthiasbeyer/imag/commit/db289dbe60073b7a5fbbff32dbe9e4552bc43e31

Call:

```
./target/debug/imag-store --debug -r /tmp create -p /test entry --content "foobakr" -h header.field=1
```

Backtrace from gdb on this line:

```
#0  libimagstore::store::Store::_update (self=0x7fffffffc3f8, entry=0x7fffffffaef8) at /home/m/archive/development/rust/imag/libimagstore/src/store.rs:179
#1  0x00005555557627c7 in libimagstore::store::FileLockEntry<'a>.Drop::drop (self=0x7fffffffaef8) at /home/m/archive/development/rust/imag/libimagstore/src/store.rs:254
#2  0x0000555555584d90 in libimagstore..store..FileLockEntry::drop.11170::h698d3282d9c3f840 () at src/libcore/clone.rs:66
#3  0x0000555555584cce in fnfn (element=...) at src/create.rs:72
#4  0x0000555555584754 in imag_store::result::Result<T, E>::map<(),closure> (self=..., op=...) at src/libcore/result.rs:484
#5  0x00005555555820be in imag_store::create::create_from_cli_spec (rt=0x7fffffffc360, matches=0x7ffff64481f0, path=0x7fffffffb638) at src/create.rs:56
#6  0x0000555555581f50 in fnfn (entry=0x7ffff6448190) at src/create.rs:31
#7  0x0000555555581ecb in imag_store::option::Option<T>::map<core::result::Result<(), imag_store::error::StoreError>,closure> (self=..., f=...) at src/libcore/option.rs:426
#8  0x00005555555816d4 in fnfn (scmd=0x7ffff64481f0) at src/create.rs:30
#9  0x0000555555581152 in imag_store::option::Option<T>::map<(),closure> (self=..., f=...) at src/libcore/option.rs:426
#10 0x00005555555810fd in imag_store::create::create (rt=0x7fffffffc360) at src/create.rs:21
#11 0x00005555555a2777 in fnfn (name=...) at src/main.rs:59
#12 0x00005555555a24a1 in imag_store::option::Option<T>::map_or_else<(),closure,closure> (self=..., default=..., f=...) at src/libcore/option.rs:470
#13 0x000055555559fbb5 in imag_store::main () at src/main.rs:49
#14 0x000055555584cd75 in sys_common::unwind::try::try_fn::h8606380137372061165 ()
#15 0x000055555584a739 in __rust_try ()
#16 0x000055555584ca10 in rt::lang_start::hbeb1bf39635abdcc9kx ()
#17 0x00005555555a2c1a in main ()
```

**Comment by matthiasbeyer** [comment]
My PR was rebased, issue is reproducible at https://github.com/matthiasbeyer/imag/commit/5069781f9f47031c5619eef17d739de0f76c91f9
